version: "3.1"

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=pets

  app-cat:
    build: ./app
    ports:
      - "8040:8040"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pets
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456

networks:
  backend:
    name: challege-cats
    driver: bridge