version: "3.1"

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=pets

  app-cat:
    build: ./app
    ports:
      - "8040:8041"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pets
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - API_CAT_KEY=9cf02f27-61da-4597-bfc1-c702fc87692c

  splunk:
    image: splunk/splunk
    restart: always
    hostname: splunk
    ports:
      - "8000:8000"
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_USERNAME=admin
      - SPLUNK_PASSWORD=Splunk@123456

networks:
  backend:
    driver: bridge